
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Stream;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

class Node {
    public String loan_acc_id;
    public String int_loan_acc_id;
    Node (){
        loan_acc_id = "";
        int_loan_acc_id ="";
    }
}
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class MainFrameUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrameUI.class.getName());

    /**
     * Creates new form MainFrameUI
     */
    public MainFrameUI() {
        initComponents();
        jTabbedPane1.setSelectedIndex(2);
        jButton1.setBackground(Color.GREEN);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GRAY);
        
        LocalDate date1 = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String formattedDate = date1.format(formatter); // Output: "20/05/2024"
        jFormattedTextField1.setText(formattedDate);
        if (DBAccessCode.g_UserMode) {
            jTabbedPane1.setEnabledAt(1, false); 
            jTabbedPane1.setEnabledAt(3, false); 
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
        }              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel29 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ML Loan Management System");

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Add Loan Account");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Update Loan Account");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("View Loan Accout Details");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Add Member");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("View Genealogical Tree");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel1.setText("Admin Options:");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel11.setText("Loan Accout Id:");

        jButton10.setBackground(new java.awt.Color(255, 255, 51));
        jButton10.setText("Read Details:");
        jButton10.addActionListener(this::jButton10ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setText("Introduced By Loan A/C:");

        jTextField9.addActionListener(this::jTextField9ActionPerformed);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("View Loan Account Details");

        jLabel24.setText("Grade:");

        jTextField11.addActionListener(this::jTextField11ActionPerformed);

        jButton12.setBackground(new java.awt.Color(255, 255, 0));
        jButton12.setText("Print");
        jButton12.addActionListener(this::jButton12ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        jTabbedPane1.addTab("", jPanel3);

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jLabel6.setText("Loan Accout Id:");

        jButton8.setBackground(new java.awt.Color(255, 255, 51));
        jButton8.setText("Read Details:");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setBackground(new java.awt.Color(255, 153, 0));
        jButton9.setText("Update");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jLabel7.setText("Member Id:");

        jLabel8.setText("Introduced By Loan A/C:");

        jLabel9.setText("Grade:");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 0));
        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jLabel15.setText("Remarks:");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Update Loan Account Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addGap(88, 88, 88))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(78, 78, 78)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton8)
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("", jPanel4);

        jLabel2.setText("Member Id:");

        jLabel3.setText("Grade:");

        jLabel4.setText("Introduced by Loan A/c ID:");

        jButton6.setBackground(new java.awt.Color(255, 255, 51));
        jButton6.setText("Create Loan A/C");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setText("Yellow");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButton7.setText("Clear");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jLabel13.setText("Date:");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.addActionListener(this::jFormattedTextField1ActionPerformed);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel14.setText("Remarks:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Create Loan Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton6)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 126, Short.MAX_VALUE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel2);

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.setText("Save Member");
        jButton11.addActionListener(this::jButton11ActionPerformed);

        jTextField10.addActionListener(this::jTextField10ActionPerformed);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel16.setText("Member ID:");

        jLabel17.setText("Remarks:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Add Member Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane4)
                                .addComponent(jButton11)
                                .addComponent(jTextField10))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("", jPanel5);

        jButton14.setBackground(new java.awt.Color(255, 255, 0));
        jButton14.setText("Update Password");
        jButton14.addActionListener(this::jButton14ActionPerformed);

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        jLabel25.setText("Password:");

        jLabel26.setText("New Password:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Change Password");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jPasswordField2)))
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(60, 60, 60)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addGap(40, 40, 40)
                .addComponent(jLabel28)
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("", jPanel6);

        jTree1.setAutoscrolls(true);
        jTree1.setRootVisible(false);
        jScrollPane5.setViewportView(jTree1);

        jLabel29.setText("Genealogical Tree for Loan A/c");

        jTextField12.setEditable(false);
        jTextField12.addActionListener(this::jTextField12ActionPerformed);

        jButton15.setBackground(new java.awt.Color(204, 255, 0));
        jButton15.setText("Show");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("", jPanel7);

        jButton13.setText("Password");
        jButton13.addActionListener(this::jButton13ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(88, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton5)
                                    .addComponent(jButton4))
                                .addGap(7, 7, 7))
                            .addComponent(jButton13))
                        .addGap(1, 1, 1)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(jButton13)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:(update Level information or status of loan account)
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:(Add members clicked)
        String sqlquery = "INSERT INTO members_tb VALUES ( ?, ?, '2026-03-10')";
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
            PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {
            String member_id = jTextField10.getText();
            String remarks = jTextArea4.getText();

            pstmt.setString(1, member_id);
            pstmt.setString(2, remarks);

            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                jLabel22.setText("Member Added");
                System.out.println("A new member was inserted successfully! :" + String.valueOf(rowsInserted));
            } else {
                jLabel22.setText("member not Added"+ String.valueOf(rowsInserted));
                System.out.println("member not Added , may be duplicate");
            }
        } catch (SQLException e) {
            jLabel22.setText("Member Add Failed, May be duplicate member Id");
            //            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:(clear add new loan accout screen )
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: (save the new loan accout with intrduser)
        String loan_acc_id = GetNewLoanAccId();
        String member_id = jTextField1.getText();
        String interduser_loan_acc_id = jTextField3.getText();
        String amt = jTextField2.getText();
        String fdate =  jFormattedTextField1.getText();
        String remarks = jTextArea2.getText();

        if (!MemberIdValidity(member_id))
        {
            jLabel5.setText("Enter Valid Member Id");
            return;
        }

        int sub_id = CheckIntraduserStatus(interduser_loan_acc_id);
        if (sub_id!=0) {

            //        String sqlquery = "INSERT INTO loan_acc_tb VALUES ('" + loan_acc_id +"','" + member_id+ "','" + interduser_loan_acc_id;
            //        sqlquery = sqlquery + "', '','','', 'Loan Acc created','" + amt + "','" ;
            //        sqlquery = sqlquery  + fdate + "');";
            String sqlquery = "INSERT INTO loan_acc_tb VALUES (?, ?, ?, ?, ?, ?, ?,?,?)";
            try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
                PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {

                pstmt.setString(1, loan_acc_id);
                pstmt.setString(2, member_id);
                pstmt.setString(3, interduser_loan_acc_id);
                pstmt.setString(4, "");
                pstmt.setString(5, "");
                pstmt.setString(6, "");
                pstmt.setString(7, remarks);
                pstmt.setString(8, "Yellow");
                pstmt.setString(9, fdate);
                //pstmt.setDate(9, java.sql.Date.valueOf(fdate));
                int rowsInserted = pstmt.executeUpdate();
                if (rowsInserted > 0) {
                    String messagetext = "New loan Accout Created with Loan A/c No:"+ loan_acc_id;
                    UpdateIntraduserLoanAcc(interduser_loan_acc_id,loan_acc_id,sub_id);
                    jLabel5.setText(messagetext);
                    System.out.println("A new record was inserted successfully!");
                } else {
                    jLabel5.setText("Loan Accout Not Created");
                    System.out.println("Add loan accout failed");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            jLabel5.setText("Allready interdused 3 loan Accouts/Loan Account is wrong ");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:(update loan accout details)
        String sqlquery = "UPDATE loan_acc_tb SET MEMBER_ID = ?, DESCRYPTION = ? WHERE LOAN_ACC_ID = ?";
        String loan_acc_id = jTextField4.getText();
        String member_id = jTextField5.getText();
        String remarks = jTextArea3.getText();
        if (!MemberIdValidity(member_id))
        {
            jLabel10.setText("Enter Valid Member Id");
            return;
        }

        // Try-with-resources automatically closes resources
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
            PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {

            // Bind values to placeholders
            pstmt.setString(1, member_id);
            pstmt.setString(2, remarks);
            pstmt.setString(3, loan_acc_id);
            // Execute the update
            int rowsAffected = pstmt.executeUpdate();
            System.out.println("Rows updated: " + rowsAffected);
            jLabel10.setText("Record Updated Successfully");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:(read loan details for update the info)
        String loan_acc_id = jTextField4.getText();
        String sqlquery = "SELECT MEMBER_ID,INT_LOAN_ACC_ID,AMOUNT,DESCRYPTION FROM loan_acc_tb WHERE LOAN_ACC_ID = '";
        sqlquery = sqlquery + loan_acc_id+ "'";
        System.out.println(sqlquery);
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
            Statement stmt = conn.createStatement())
        {

            //System.out.println("Connected to the database successfully!");
            ResultSet rs = stmt.executeQuery(sqlquery);

            // Step 4: Process the result set
            if (rs.next()) {
                String member_id = rs.getString("MEMBER_ID");
                String intrduser_loan_id = rs.getString("INT_LOAN_ACC_ID");
                String amt = rs.getString("AMOUNT");
                String remarks = rs.getString("DESCRYPTION");

                jTextField5.setText(member_id);
                jTextField7.setText(intrduser_loan_id);
                if  (amt.equals("White")) jTextField6.setBackground(Color.WHITE);
                if  (amt.equals("Green")) jTextField6.setBackground(Color.GREEN);
                if  (amt.equals("Yellow")) jTextField6.setBackground(Color.YELLOW);
                jTextField6.setVisible(true);
                jTextField6.setText(amt);
                jTextArea3.setText(remarks);
                jLabel10.setText("Record Found");
            }
            else {
                jLabel10.setText("Record Not Found");
            }
            // System.out.println("Login Failed!");

        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here(read details - display loan hirarchi):
        String loan_acc_id = jTextField9.getText();
        g_loan_acc_no = loan_acc_id;
        jTextField12.setText(g_loan_acc_no);
        String sqlquery = "SELECT MEMBER_ID,INT_LOAN_ACC_ID,AMOUNT,DESCRYPTION FROM loan_acc_tb WHERE LOAN_ACC_ID = '";
        sqlquery = sqlquery + loan_acc_id+ "'";
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
            Statement stmt = conn.createStatement())
        {
            ResultSet rs = stmt.executeQuery(sqlquery);
            if (rs.next()) {
                String member_id = rs.getString("MEMBER_ID");
                g_MemberID = member_id;
                String intrduser_loan_id = rs.getString("INT_LOAN_ACC_ID");
                String amt = rs.getString("AMOUNT");
                String remarks = rs.getString("DESCRYPTION");
                g_remarks = remarks;
                jTextField8.setText(intrduser_loan_id);
                jLabel23.setText("Record Found");
                jTextField11.setText(amt);
                jTextField11.setBackground(Color.YELLOW);
            }
            else {
                jLabel23.setText("Record Not Found");
            }
            // System.out.println("Login Failed!");

        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }

        ReadLoanDetails(loan_acc_id);
        String buffer = "";

        Iterator<ArrayList> root_iter    = DBAccessCode.root_list.iterator();
        int level_index = 1;
        while (root_iter.hasNext()) {
            ArrayList<Node> level_list;

            level_list = root_iter.next();
            int no_nodes = level_list.size();
            buffer = buffer +"\nLevel - "+ String.valueOf(level_index) +"[Loan A/c Ids:" + String.valueOf(no_nodes) + "]\n";
            Iterator<Node> level_iter    = level_list.iterator();
            while (level_iter.hasNext()) {
                Node n = level_iter.next();
                buffer = buffer + n.loan_acc_id +" (" + n.int_loan_acc_id + ") \t";
            }
            if (no_nodes == 3 && level_index ==1){
                UpdateGrade("White",loan_acc_id);
                jTextField11.setText("White");
                jTextField11.setBackground(Color.WHITE);

            } else if (no_nodes == 9 && level_index == 2 ) {
                UpdateGrade("Green",loan_acc_id);
                jTextField11.setText("Green");
                jTextField11.setBackground(Color.GREEN);
            }
            jTextField11.setVisible(true);

            level_index = level_index+1;
            buffer = buffer + "\n";
        }
        jTextArea1.setText(buffer);
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode newRoot = new DefaultMutableTreeNode(g_loan_acc_no);
        model.setRoot(newRoot);
        model.reload();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GREEN);
        jButton13.setBackground(Color.GRAY);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GREEN);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GREEN);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GRAY);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GREEN);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GRAY);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        jButton1.setBackground(Color.GREEN);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here: -->print pdf report
        String loan_acc_no = jTextField9.getText();//loab acc id
        String int_loan_acc_id = jTextField8.getText();// int_loan_acc_id

        LocalDate date1 = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String today_date = date1.format(formatter); // Output: "20/05/2024"

        try {
            Document document = new Document();
            //today_date = get_date()
            PdfWriter.getInstance(document, new FileOutputStream("C:\\MLLS_Reports\\"+loan_acc_no+".pdf"));
            document.open();
            // write Loan Account details, Refrence and Address
            Paragraph paragraph = new Paragraph("Loan Acc No:" +loan_acc_no +"\n As on Date:" +today_date+ "\n "+ "Member Id:"+ g_MemberID +"\n"+"Interdused By:" + int_loan_acc_id);
            paragraph.setAlignment(Element.ALIGN_CENTER);  
            document.add(paragraph);

            Iterator<ArrayList> root_iter    = DBAccessCode.root_list.iterator();
            int level_index = 1;
            while (root_iter.hasNext()) {
                
                ArrayList<Node> level_list;

                level_list = root_iter.next();
                int no_nodes = level_list.size();
                
                String leveStr = "\nLevel - "+ String.valueOf(level_index) +"[Number of Loan A/c Ids:" + String.valueOf(no_nodes) + "] \n\n";
                Paragraph paragraph1 = new Paragraph(leveStr);
                paragraph1.setAlignment(Element.ALIGN_LEFT);  
                document.add(paragraph1); 
                
                Iterator<Node> level_iter    = level_list.iterator();                
                PdfPTable table = new PdfPTable(2);

                Stream.of("Loan Account ", "Introducer Loan Account")
                  .forEach(columnTitle -> {
                    PdfPCell header = new PdfPCell();
                    header.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    header.setBorderWidth(2);
                    header.setPhrase(new Phrase(columnTitle));
                    table.addCell(header);
                });
            
                while (level_iter.hasNext()) {
                    Node n = level_iter.next();
                    table.addCell(n.loan_acc_id );
                    table.addCell(n.int_loan_acc_id);
                }
                document.add(table);
                level_index = level_index+1;
            }

            document.close();
            jLabel30.setText("open folder C:\\MLLS_Reports and see pdf");
       }
       catch (Exception e) {
            jLabel30.setText("Issues in pdf creation at C:\\MLLS_Reports");
       }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here: - >password change code
        jTabbedPane1.setSelectedIndex(4);
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton13.setBackground(Color.GREEN);
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:  --- update password
        String user_id = "";
        String p_word ="";
        String e_pword ="";
        String n_pword="";

        if (DBAccessCode.g_UserMode) {
            user_id = "emp";
        } else {
           user_id = "admin" ;
        }
        char ch[];
        ch = jPasswordField1.getPassword();
        e_pword = String.valueOf(ch);

        ch = jPasswordField2.getPassword();
        n_pword = String.valueOf(ch);
        
        String sqlquery1 = "SELECT P_WORD FROM user_tb WHERE USR_ID = '";
        sqlquery1 = sqlquery1 + user_id+ "'";
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
            Statement stmt = conn.createStatement())
        {
            ResultSet rs = stmt.executeQuery(sqlquery1);
            if (rs.next()) {
                p_word = rs.getString("P_WORD");
                jLabel28.setText("User Found");
            }
            else {
                jLabel28.setText("User Not Found");
            }
        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }

        if (p_word.equals(e_pword)){
            String sqlquery = "UPDATE user_tb SET P_WORD = ? WHERE USR_ID = ?";
            // Try-with-resources automatically closes resources
            try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
                PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {

                // Bind values to placeholders
                pstmt.setString(1, n_pword);
                pstmt.setString(2, user_id);

                // Execute the update
                int rowsAffected = pstmt.executeUpdate();
                System.out.println("Password updated: " + rowsAffected);
                jLabel28.setText("Password Updated Successfully");

            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            jLabel28.setText("Entered Wrong Password");
        }              
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here: Genarology code
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode newRoot = new DefaultMutableTreeNode(g_loan_acc_no);
        model.setRoot(newRoot);
        model.reload();
        
        ArrayList<DefaultMutableTreeNode> tree_node_list = new ArrayList<>();
        tree_node_list.add(newRoot);
        
        Iterator<ArrayList> root_iter    = DBAccessCode.root_list.iterator();

        while (root_iter.hasNext()) {

            ArrayList<Node> level_list;
            level_list = root_iter.next();

            Iterator<Node> level_iter    = level_list.iterator();                

            while (level_iter.hasNext()) {
                Node n = level_iter.next();
                DefaultMutableTreeNode mn = tree_node_list.getFirst();
                if (n.int_loan_acc_id.equals(mn.toString())) {
                    DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(n.loan_acc_id);
                    mn.add(newNode);
                    tree_node_list.add(newNode);
                    System.out.println(mn.toString());
                } else {
                        tree_node_list.removeFirst();
                        if (!tree_node_list.isEmpty()) {
                            mn = tree_node_list.getFirst();
                            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(n.loan_acc_id);
                            mn.add(newNode);
                            tree_node_list.add(newNode);
                        }
                }                
            }
            tree_node_list.removeFirst();
        }
        model.setRoot(newRoot);
        model.reload();
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrameUI().setVisible(true));
    }

    private String g_MemberID;
    private String g_loan_acc_no;
    private String g_remarks;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private String GetNewLoanAccId() {
    //    int number = ThreadLocalRandom.current().nextInt(100_000, 1_000_000);
        int number = ThreadLocalRandom.current().nextInt(100_00000, 1_000_00000);
        String str = String.format("%08d", number);
        return str ;
    }

    private int CheckIntraduserStatus(String interduser_loan_acc_id) {
        int sub_id = 0;
        String sqlquery = "SELECT SUB_LOAN_ACC_ID1,SUB_LOAN_ACC_ID2,SUB_LOAN_ACC_ID3 FROM loan_acc_tb WHERE LOAN_ACC_ID = '";
        sqlquery = sqlquery + interduser_loan_acc_id+ "'";
        System.out.println(sqlquery);
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             Statement stmt = conn.createStatement()) 
        {
            //System.out.println("Connected to the database successfully!");
            ResultSet rs = stmt.executeQuery(sqlquery);

            // Step 4: Process the result set
            if (rs.next()) {
                String sub_loanId1 = rs.getString("SUB_LOAN_ACC_ID1");
                String sub_loanId2 = rs.getString("SUB_LOAN_ACC_ID2");
                String sub_loanId3 = rs.getString("SUB_LOAN_ACC_ID3");
                
                if (sub_loanId1.isEmpty()) {
                    sub_id = 1;
                } else if (sub_loanId2.isEmpty()) {
                    sub_id = 2;
                } else if (sub_loanId3.isEmpty()) {
                    sub_id = 3;
                } else {
                    sub_id = 0;
                }
                System.out.println( sub_loanId1 +" "+sub_loanId2+ " "+ sub_loanId3);
                System.out.println("interduser found!!! "+ String.valueOf(sub_id));  
            }   else {
                sub_id = 0;
                System.out.println("interduser not found!!!" + String.valueOf(sub_id));                
            }
            // System.out.println("Login Failed!");
            
        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }
        return sub_id;
    }

    private void UpdateIntraduserLoanAcc(String interduser_loan_acc_id, String loan_acc_id, int sub_id) {
        
        String colum_name = "SUB_LOAN_ACC_ID1";
        if (sub_id == 1) {
            colum_name = "SUB_LOAN_ACC_ID1";
        } else if (sub_id == 2) {
            colum_name = "SUB_LOAN_ACC_ID2";
        } else if (sub_id == 3) {
            colum_name = "SUB_LOAN_ACC_ID3";
        }
        String sqlquery = "UPDATE loan_acc_tb SET "+ colum_name + " = ? WHERE LOAN_ACC_ID = ?";

        // Try-with-resources automatically closes resources
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {

            // Bind values to placeholders
            pstmt.setString(1, loan_acc_id);
            pstmt.setString(2, interduser_loan_acc_id); 
            // Execute the update
            int rowsAffected = pstmt.executeUpdate();
            System.out.println("Interduser accout Rows updated: " + rowsAffected);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private boolean MemberIdValidity(String member_id) {
        boolean retVal = false;
        String sqlquery = "SELECT MEMBER_ID FROM members_tb WHERE MEMBER_ID = '";
        sqlquery = sqlquery + member_id+ "'";
        System.out.println(sqlquery);
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             Statement stmt = conn.createStatement()) 
        {
            //System.out.println("Connected to the database successfully!");
            ResultSet rs = stmt.executeQuery(sqlquery);

            // Step 4: Process the result set
            if (rs.next()) {
                retVal = true;
            }   else {
                retVal = false;
            }
            // System.out.println("Login Failed!");            
        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
//            e.printStackTrace();
        }
        return retVal;
    }

    private void ReadLoanDetails(String loan_acc_id) {
        DBAccessCode.root_list.clear();
        ArrayList<Node> level_list =   new ArrayList<>();
        ArrayList<Node> sub_level_list = null;
        String sqlquery = "SELECT SUB_LOAN_ACC_ID1,SUB_LOAN_ACC_ID2,SUB_LOAN_ACC_ID3 FROM loan_acc_tb WHERE LOAN_ACC_ID = '";
        sqlquery = sqlquery + loan_acc_id+ "'";

        System.out.println(sqlquery);
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             Statement stmt = conn.createStatement()) 
        {
            //System.out.println("Connected to the database successfully!");
            ResultSet rs = stmt.executeQuery(sqlquery);
            // Step 4: Process the result set
            if (rs.next()) {
                String sub_loanId1 = rs.getString("SUB_LOAN_ACC_ID1");
                String sub_loanId2 = rs.getString("SUB_LOAN_ACC_ID2");
                String sub_loanId3 = rs.getString("SUB_LOAN_ACC_ID3");
                
                if (sub_loanId1.isEmpty()) {
                    ;
                } else if (sub_loanId2.isEmpty()) {
                    Node n = new Node();
                    n.loan_acc_id = sub_loanId1;
                    n.int_loan_acc_id = loan_acc_id;
                    level_list.add(n);
                } else if (sub_loanId3.isEmpty()) {
                    Node n1 = new Node();
                    n1.loan_acc_id = sub_loanId1;
                    n1.int_loan_acc_id = loan_acc_id;
                    level_list.add(n1);
                    
                    Node n2 = new Node();
                    n2.loan_acc_id = sub_loanId2;
                    n2.int_loan_acc_id = loan_acc_id;
                    level_list.add(n2);
                } else {
                    Node n1 = new Node();
                    n1.loan_acc_id = sub_loanId1;
                    n1.int_loan_acc_id = loan_acc_id;
                    level_list.add(n1);
                    
                    Node n2 = new Node();
                    n2.loan_acc_id = sub_loanId2;
                    n2.int_loan_acc_id = loan_acc_id;
                    level_list.add(n2);
                    
                    Node n3 = new Node();
                    n3.loan_acc_id = sub_loanId3;
                    n3.int_loan_acc_id = loan_acc_id;
                    level_list.add(n3);
                }
            }   else {
                System.out.println("loan account not found!!!" );                
            }
            // System.out.println("Login Failed!");
            
        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }
        while (!level_list.isEmpty()) {
            DBAccessCode.root_list.add(level_list);
            sub_level_list = AddSubLoanAccounts(level_list);
            level_list = sub_level_list;            
        }

    }
    
    private ArrayList<Node> SubLoanDetails(String loan_acc_id) {
        
        ArrayList<Node> node_list =   new ArrayList<>();
        String sqlquery = "SELECT SUB_LOAN_ACC_ID1,SUB_LOAN_ACC_ID2,SUB_LOAN_ACC_ID3 FROM loan_acc_tb WHERE LOAN_ACC_ID = '";
        sqlquery = sqlquery + loan_acc_id+ "'";
        System.out.println(sqlquery);

        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             Statement stmt = conn.createStatement()) 
        {
            //System.out.println("Connected to the database successfully!");
            ResultSet rs = stmt.executeQuery(sqlquery);
            // Step 4: Process the result set
            if (rs.next()) {
                String sub_loanId1 = rs.getString("SUB_LOAN_ACC_ID1");
                String sub_loanId2 = rs.getString("SUB_LOAN_ACC_ID2");
                String sub_loanId3 = rs.getString("SUB_LOAN_ACC_ID3");
                
                if (sub_loanId1.isEmpty()) {
                    return node_list;
                } else if (sub_loanId2.isEmpty()) {
                    Node n = new Node();
                    n.loan_acc_id = sub_loanId1;
                    n.int_loan_acc_id = loan_acc_id;
                    node_list.add(n);
                    return node_list;
                } else if (sub_loanId3.isEmpty()) {
                    Node n1 = new Node();
                    n1.loan_acc_id = sub_loanId1;
                    n1.int_loan_acc_id = loan_acc_id;
                    node_list.add(n1);
                    
                    Node n2 = new Node();
                    n2.loan_acc_id = sub_loanId2;
                    n2.int_loan_acc_id = loan_acc_id;
                    node_list.add(n2);
                    return node_list;
                } else {
                    Node n1 = new Node();
                    n1.loan_acc_id = sub_loanId1;
                    n1.int_loan_acc_id = loan_acc_id;
                    node_list.add(n1);
                    
                    Node n2 = new Node();
                    n2.loan_acc_id = sub_loanId2;
                    n2.int_loan_acc_id = loan_acc_id;
                    node_list.add(n2);
                    
                    Node n3 = new Node();
                    n3.loan_acc_id = sub_loanId3;
                    n3.int_loan_acc_id = loan_acc_id;
                    node_list.add(n3);
                    return node_list;
                }
            }   else {
                System.out.println("loan account not found!!!" );                
            }
            
        } catch (SQLException e) {
            System.err.println("Connection error: " + e.getMessage());
//            e.printStackTrace();
        }
        return node_list;
    }
    
    private ArrayList<Node> AddSubLoanAccounts(ArrayList<Node> level_node_list) {
        
        ArrayList<Node> sub_level_list =   new ArrayList<>();
        
        Iterator<Node> level_iter    = level_node_list.iterator();
        while (level_iter.hasNext()) {
                Node n = level_iter.next();
                sub_level_list.addAll(SubLoanDetails(n.loan_acc_id));
        }
        return sub_level_list;
    }

    private void UpdateGrade(String grade,String loan_acc_id) {
        String sqlquery = "UPDATE loan_acc_tb SET "+ "AMOUNT" + " = ? WHERE LOAN_ACC_ID = ?";

        // Try-with-resources automatically closes resources
        try (Connection conn = DriverManager.getConnection(DBAccessCode.g_url, DBAccessCode.g_user, DBAccessCode.g_password);
             PreparedStatement pstmt = conn.prepareStatement(sqlquery)) {

            // Bind values to placeholders
            pstmt.setString(1, grade);
            pstmt.setString(2, loan_acc_id); 
            // Execute the update
            int rowsAffected = pstmt.executeUpdate();
            System.out.println("Grade updated: " + rowsAffected);

        } catch (SQLException e) {
            e.printStackTrace();
        }
       
    }
}
